proiectFinal/aplicatie1/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

from aplicatie1 import views
from aplicatie1.views import MovieDetail

app_name = 'movieApplication'

urlpatterns = [
    path('', views.MoviesView.as_view(), name='lista_filme'),
    path('addMovie/', views.CreateMoviesView.as_view(), name='addMovie'),
    path('topRatedMovie/', views.MoviesTopRated.as_view(), name='topRatedMovie'),
    path('mostWatchedMovie/', views.MoviesMostWatched.as_view(), name='mostWatchedMovie'),
    path('recentlyAddedMovie/', views.MoviesRecentlyAdded.as_view(), name='recentlyAddedMovie'),
    path('<int:pk>/updateMovie/', views.UpdateMoviesView.as_view(), name='updateMovie'),
    path('<int:pk>/deleteMovie/', views.delete_movies, name='deleteMovie'),
    path('<int:pk>/activateMovie/', views.activate_movies, name='activateMovie'),
    path('inactiveMovies', views.MoviesInactiveView.as_view(), name='inactiveMovies'),
    path('searchMovies/', views.search_movies, name='searchMovies'),
    path('<int:pk>/movieDetails/', views.MovieDetail.as_view(), name='movieDetails'),
    path('register/', views.registerPage, name='register'),

    path('action/', views.MoviesAction.as_view(), name='action'),
    path('drama/', views.MoviesDrama.as_view(), name='drama'),
    path('comedy/', views.MoviesComedy.as_view(), name='comedy'),
    path('romance/', views.MoviesRomance.as_view(), name='romance'),
    path('adventure/', views.MoviesAdventure.as_view(), name='adventure'),
    path('love/', views.MoviesLove.as_view(), name='love'),
    path('cartoons/', views.MoviesCartoons.as_view(), name='cartoons'),


    # path('topRatedMovies', views.MoviesTopRated.as_view(), name='topRatedMovies'),
    # path('mostWatchedMovies', views.MoviesMostWatched.as_view(), name='mostWatchedMovies'),
    # path('recentlyAddedMovies', views.MoviesRecentlyAdded.as_view(), name='recentlyAddedMovies'),


]

proiectFinal/proiectFinal/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include


from proiectFinal import settings
from userprofile import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('movies/', include('aplicatie1.urls')),
    path('userprofile/', include('userprofile.urls')),


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proiectFinal/aplicatie1/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.

CATEGORY_CHOICES = (
    ('action', 'ACTION'),
    ('drama', 'DRAMA'),
    ('comedy', 'COMEDY'),
    ('romance', 'ROMANCE'),
    ('adventure', 'ADVENTURE'),
    ('love', 'LOVE'),
    ('cartoons', 'CARTOONS'),
)

LANGUAGE_CHOICES = (
    ('english', 'ENGLISH'),
    ('german', 'GERMAN'),
    ('spanish', 'SPANISH'),
)

STATUS_CHOICES = (
    ('RECENTLY ADDED', 'RECENTLY ADDED'),
    ('MOST WATCHED', 'MOST WATCHED'),
    ('TOP RATED', 'TOP RATED'),
)
class Movie(models.Model):

    title = models.CharField(max_length=100)
    description = models.CharField(max_length=1500)
    release_date = models.DateField()
    duration = models.CharField(max_length=10)
    budget = models.CharField(max_length=25)
    rating = models.FloatField()
    poster = models.ImageField(upload_to='movies')
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=12)
    language = models.CharField(choices=LANGUAGE_CHOICES, max_length=12)
    status = models.CharField(choices=STATUS_CHOICES, max_length=20)
    trailer_url = models.CharField(max_length=255, null=True, blank=True)
    active = models.BooleanField(default=1)


    def __str__(self):
        return f"{self.title} - {self.description} - {self.release_date} - {self.duration} - {self.budget} - {self.category} - {self.description} - {self.language} - {self.status}"

proiectFinal/aplicatie1/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

proiectFinal/aplicatie1/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm

# Create your views here.
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView
from django.views.generic.detail import DetailView


from aplicatie1.models import Movie


def registerPage(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()

    context = {'form':form}
    return render(request, 'aplicatie1/register.html', context)


def loginPage(request):
    context = {}
    return render(request, 'aplicatie1/login.html', context)

class MoviesView(LoginRequiredMixin, ListView):
    model = Movie
    template_name = 'aplicatie1/movies_index.html'
    paginate_by = 8
    queryset = model.objects.filter(active=1)
    context_object_name = 'moviesList'

    def get_context_data(self, *args, **kargs):
        data = super(MoviesView, self).get_context_data( *args, **kargs)
        data['moviesL'] = self.model.objects.filter(active=1)
        return data


class CreateMoviesView(LoginRequiredMixin, CreateView):
    model = Movie
    fields = ['title', 'description', 'release_date', 'duration', 'budget', 'rating', 'poster', 'category', 'language', 'status', 'trailer_url']
    template_name = 'aplicatie1/movies_form.html'


    def get_success_url(self):
        return reverse('movieApplication:lista_filme')



class UpdateMoviesView(LoginRequiredMixin, UpdateView):
    model = Movie
    fields = ['title', 'description', 'release_date', 'duration', 'budget', 'rating', 'poster', 'category', 'language', 'status', 'trailer_url']
    template_name = 'aplicatie1/movies_form.html'

    def get_success_url(self):
        return reverse('movieApplication:lista_filme')



@login_required
def search_movies(request):
    if request.method == "POST":
        searched = request.POST['searched']
        movies = Movie.objects.filter(title__contains=searched)
        return render(request, 'aplicatie1/search_movies.html', {'searched': searched, 'movies': movies})
    else:
        return render(request, 'aplicatie1/search_movies.html', {})

@login_required
def delete_movies(request, pk):
    Movie.objects.filter(id=pk).update(active=0)
    return redirect('movieApplication:lista_filme')

@login_required
def activate_movies(request, pk):
    Movie.objects.filter(id=pk).update(active=1)
    return redirect('movieApplication:lista_filme')


class MoviesInactiveView(LoginRequiredMixin, ListView):
    model = Movie
    template_name = 'aplicatie1/movies_index.html'
    paginate_by = 8
    queryset = model.objects.filter(active=0)
    context_object_name = 'locations'

    def get_context_data(self, *args, **kargs):
        data = super(MoviesInactiveView, self).get_context_data( *args, **kargs)
        data['moviesL'] = self.model.objects.filter(active=0)
        return data


class MoviesTopRated(LoginRequiredMixin,ListView):
    model = Movie
    template_name = 'aplicatie1/movies_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(MoviesTopRated, self).get_context_data( *args, **kargs)
        data['moviesL'] = self.model.objects.filter(status='TOP RATED')
        return data


class MoviesMostWatched(LoginRequiredMixin,ListView):
    model = Movie
    template_name = 'aplicatie1/movies_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(MoviesMostWatched, self).get_context_data( *args, **kargs)
        data['moviesL'] = self.model.objects.filter(status='MOST WATCHED')
        return data

class MoviesRecentlyAdded(LoginRequiredMixin,ListView):
    model = Movie
    template_name = 'aplicatie1/movies_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(MoviesRecentlyAdded, self).get_context_data( *args, **kargs)
        data['moviesL'] = self.model.objects.filter(status='RECENTLY ADDED')
        return data


class MovieDetail(LoginRequiredMixin, DetailView):
    model = Movie
    template_name = 'aplicatie1/movie_details.html'

    def get_context_data(self, *args, **kargs):
        data = super(MovieDetail, self).get_context_data(*args, **kargs)
        data['moviesL'] = self.model.objects.filter(active=1)
        return data




class MoviesAction(LoginRequiredMixin,ListView):
    model = Movie
    template_name = 'aplicatie1/movies_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(MoviesAction, self).get_context_data( *args, **kargs)
        data['moviesL'] = self.model.objects.filter(category='action')
        return data


class MoviesDrama(LoginRequiredMixin,ListView):
    model = Movie
    template_name = 'aplicatie1/movies_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(MoviesDrama, self).get_context_data( *args, **kargs)
        data['moviesL'] = self.model.objects.filter(category='drama')
        return data

class MoviesComedy(LoginRequiredMixin,ListView):
    model = Movie
    template_name = 'aplicatie1/movies_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(MoviesComedy, self).get_context_data( *args, **kargs)
        data['moviesL'] = self.model.objects.filter(category='comedy')
        return data


class MoviesRomance(LoginRequiredMixin, ListView):
    model = Movie
    template_name = 'aplicatie1/movies_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(MoviesRomance, self).get_context_data(*args, **kargs)
        data['moviesL'] = self.model.objects.filter(category='romance')
        return data


class MoviesAdventure(LoginRequiredMixin, ListView):
    model = Movie
    template_name = 'aplicatie1/movies_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(MoviesAdventure, self).get_context_data(*args, **kargs)
        data['moviesL'] = self.model.objects.filter(category='adventure')
        return data


class MoviesLove(LoginRequiredMixin, ListView):
    model = Movie
    template_name = 'aplicatie1/movies_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(MoviesLove, self).get_context_data(*args, **kargs)
        data['moviesL'] = self.model.objects.filter(category='love')
        return data

class MoviesCartoons(LoginRequiredMixin, ListView):
    model = Movie
    template_name = 'aplicatie1/movies_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(MoviesCartoons, self).get_context_data(*args, **kargs)
        data['moviesL'] = self.model.objects.filter(category='cartoons')
        return data

proiectFinal/templates/aplicatie1/login.html
<!--{% extends 'base.html' %}-->

<!--<html>-->

<!--<head>-->
<!--	<title>Login</title>-->
<!--	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">-->
<!--	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>-->
<!--	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">-->


<!--	<style>-->
<!--		body,-->
<!--		html {-->
<!--			margin: 0;-->
<!--			padding: 0;-->
<!--			height: 100%;-->
<!--			background: #7abecc !important;-->
<!--		}-->
<!--		.user_card {-->
<!--			width: 350px;-->
<!--			margin-top: auto;-->
<!--			margin-bottom: auto;-->
<!--			background: #74cfbf;-->
<!--			position: relative;-->
<!--			display: flex;-->
<!--			justify-content: center;-->
<!--			flex-direction: column;-->
<!--			padding: 10px;-->
<!--			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);-->
<!--			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);-->
<!--			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);-->
<!--			border-radius: 5px;-->

<!--		}-->

<!--		.form_container {-->
<!--			margin-top: 20px;-->
<!--		}-->

<!--		#form-title{-->
<!--			color: #fff;-->

<!--		}-->

<!--		.login_btn {-->
<!--			width: 100%;-->
<!--			background: #33ccff !important;-->
<!--			color: white !important;-->
<!--		}-->
<!--		.login_btn:focus {-->
<!--			box-shadow: none !important;-->
<!--			outline: 0px !important;-->
<!--		}-->
<!--		.login_container {-->
<!--			padding: 0 2rem;-->
<!--		}-->
<!--		.input-group-text {-->
<!--			background: #f7ba5b !important;-->
<!--			color: white !important;-->
<!--			border: 0 !important;-->
<!--			border-radius: 0.25rem 0 0 0.25rem !important;-->
<!--		}-->
<!--		.input_user,-->
<!--		.input_pass:focus {-->
<!--			box-shadow: none !important;-->
<!--			outline: 0px !important;-->
<!--		}-->

<!--		#messages{-->
<!--			background-color: grey;-->
<!--			color: #fff;-->
<!--			padding: 10px;-->
<!--			margin-top: 10px;-->
<!--		}-->
<!--	</style>-->

<!--</head>-->
<!--<body>-->
<!--	<div class="container h-100">-->
<!--		<div class="d-flex justify-content-center h-100">-->
<!--			<div class="user_card">-->
<!--				<div class="d-flex justify-content-center">-->


<!--					<h3 id="form-title">LOGIN</h3>-->
<!--				</div>-->
<!--				<div class="d-flex justify-content-center form_container">-->
<!--					<form method="POST" action="">-->
<!--						<div class="input-group mb-3">-->
<!--							<div class="input-group-append">-->
<!--								<span class="input-group-text"><i class="fas fa-user"></i></span>-->
<!--							</div>-->
<!--							<input type="text" name="username" placeholder="Username..." class="form-control">-->
<!--						</div>-->
<!--						<div class="input-group mb-2">-->
<!--							<div class="input-group-append">-->
<!--								<span class="input-group-text"><i class="fas fa-key"></i></span>-->
<!--							</div>-->
<!--								<input type="password" name="password" placeholder="Password..." class="form-control" >-->
<!--						</div>-->

<!--							<div class="d-flex justify-content-center mt-3 login_container">-->
<!--				 				<input class="btn login_btn" type="submit" value="Login">-->
<!--				   			</div>-->
<!--					</form>-->

<!--				</div>-->

<!--				<div class="mt-4">-->
<!--					<div class="d-flex justify-content-center links">-->
<!--						Don't have an account? <a href="{% url 'register' %}" class="ml-2">Sign Up</a>-->
<!--					</div>-->

<!--				</div>-->
<!--			</div>-->
<!--		</div>-->
<!--	</div>-->
<!--</body>-->

<!--</html>-->

proiectFinal/templates/aplicatie1/movie_details.html
{% extends 'base.html' %}
{% block content %}
{% if request.user.is_superuser %}
<a class="btn btn-danger" href="{% url 'movieApplication:addMovie' %}">Add movie</a>
{% endif %}

<tbody>
<br/>
{% if request.user.is_superuser is False %}
<div  align="center">
<div class="card border-dark md-1" style="max-width: 1100px;" align="left" >
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{ object.poster.url }}" class="img-fluid rounded-start" width="950" height="1250">
    </div>
    <div class="col-md-8">
      <div class="">
       <h5 class="card-title" style="font-size: 40px; font-family:courier;"><b>{{ object.title }}</b></h5>
        <p class="card-text" style="font-family:courier;"><b><i>{{ object.description }}</i></b></p>
        <p class="card-text" style="font-size: 20px; font-family:courier;"><b>Release date: {{ object.release_date}}</b></p>
        <p class="card-text" style="font-size: 20px; font-family:courier;"><b>Duration: {{ object.duration}}</b></p>
          <p class="card-text" style="font-size: 20px; font-family:courier;"><b>Rating: {{ object.rating }}</b></p>
          <p class="card-text" style="font-size: 20px; font-family:courier;"><b>Budget: {{ object.budget }}</b></p>
          <p class="card-text" style="font-size: 20px; font-family:courier;"><b>Category: {{ object.category }}</b></p>
          <p class="card-text" style="font-size: 20px; font-family:courier;"><b>Language: {{ object.language }}</b></p>
          <p class="card-text" style="font-size: 20px; font-family:courier;"><b>Status: {{ object.status }}</b></p>
          <p class="text-muted" style="font-size: 20px; font-family:courier;"><b><a class="btn btn-info rounded-pill" href="{{ object.trailer_url }}">Click here for trailer</a></b></p>
      </div>
    </div>
  </div>
</div>
    </div>
<br>
<div align="center">
<b><a href="{% url 'movieApplication:lista_filme' %}"><input type="button" value="Back" class="btn btn-warning rounded-pill" style="font-size: 20px; font-family:courier;" /></a></b>
    </div>
{% endif %}
</tbody>

{% endblock %}

proiectFinal/templates/aplicatie1/movies_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
     <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
         {% for field in form %}
         <br>
                {% if field.label == 'poster' %}
                    {{ field.label }} <img src="{{ field.poster }}">
                {% else %}
         <div align="center"><b>{{ field.label }} {{ field }} {{ field.errors }}</b></div>
         <br>
         <br>
                {% endif %}
            {% endfor %}
         <br>
        <div align="center"><button class="btn btn-success" type="submit">Save</button></div>
    </form>

{% endblock %}

proiectFinal/templates/aplicatie1/movies_index.html
{% extends 'base.html' %}
{% block content %}

<p>
<!--<div class="btn-group">-->
<!--  <button type="button" class="btn btn-warning">Categories</button>-->
<!--  <button type="button" class="btn btn-warning dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--    <span class="sr-only">Toggle Dropdown</span>-->
<!--  </button>-->
<!--  <div class="dropdown-menu">-->
<!--   <a class="dropdown-item" href="{% url 'movieApplication:action' %}"  style="font-family:fourier">ACTION</a>-->
<!--<a class="dropdown-item" href="{% url 'movieApplication:drama' %}"  style="font-family:fourier">DRAMA</a>-->
<!--<a class="btn btn-warning rounded-pill" href="{% url 'movieApplication:comedy' %}"  style="font-family:fourier">COMEDY</a>-->
<!--<a class="btn btn-warning rounded-pill" href="{% url 'movieApplication:romance' %}"  style="font-family:fourier">ROMANCE</a>-->
<!--<a class="btn btn-warning rounded-pill" href="{% url 'movieApplication:adventure' %}"  style="font-family:fourier">ADVENTURE</a>-->
<!--<a class="btn btn-warning rounded-pill" href="{% url 'movieApplication:love' %}"  style="font-family:fourier">LOVE</a>-->
<!--<a class="btn btn-warning rounded-pill" href="{% url 'movieApplication:cartoons' %}"  style="font-family:fourier">CARTOONS</a>-->
<!--  </div>-->
<!--</div>-->
<div align="center">
<a class="btn btn-warning rounded-pill" href="{% url 'movieApplication:action' %}"  style="font-family:fourier">ACTION</a>
<a class="btn btn-warning rounded-pill" href="{% url 'movieApplication:drama' %}"  style="font-family:fourier">DRAMA</a>
<a class="btn btn-warning rounded-pill" href="{% url 'movieApplication:comedy' %}"  style="font-family:fourier">COMEDY</a>
<a class="btn btn-warning rounded-pill" href="{% url 'movieApplication:romance' %}"  style="font-family:fourier">ROMANCE</a>
<a class="btn btn-warning rounded-pill" href="{% url 'movieApplication:adventure' %}"  style="font-family:fourier">ADVENTURE</a>
<a class="btn btn-warning rounded-pill" href="{% url 'movieApplication:love' %}"  style="font-family:fourier">LOVE</a>
<a class="btn btn-warning rounded-pill" href="{% url 'movieApplication:cartoons' %}"  style="font-family:fourier">CARTOONS</a>
        <br>
        <br>
<a class="btn btn-warning rounded-pill" href="{% url 'movieApplication:topRatedMovie' %}"  style="font-family:fourier">TOP RATED MOVIES</a>
<a class="btn btn-warning rounded-pill" href="{% url 'movieApplication:mostWatchedMovie' %}"  style="font-family:fourier">MOST WATCHED MOVIES</a>
<a class="btn btn-warning rounded-pill" href="{% url 'movieApplication:recentlyAddedMovie' %}"  style="font-family:fourier">RECENTLY ADDED MOVIES</a>
<a class="btn btn-warning rounded-pill" href="{% url 'movieApplication:lista_filme' %}"  style="font-family:fourier">ALL MOVIES</a>



</div>
</p>

<table class="table table-striped">
    <thead class="thead-dark">
    {% if request.user.is_superuser %}
    <tr>
        <th>Index</th>
        <th>Title</th>
        <th>Description</th>
        <th>Release_date</th>
        <th>Duration</th>
        <th>Budget</th>
        <th>Rating</th>
        <th>Poster</th>
        <th>Category</th>
        <th>Language</th>
        <th>Status</th>
        <th>Trailer</th>
        <th>State</th>
        <th>Actions</th>
    </tr>
    {% endif %}
    </thead>
    <tbody>
    <div class="col-md-12">
        <div class="row">
            {% for item in moviesL %}
            {% if request.user.is_superuser is False %}
            <div class="col-md-3">
                <div class="card" style="width: 20rem;" align="center">
                    <img class="card-img-top" src="{{ item.poster.url }}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title" style="font-size: 25px; font-family:fourier;"><b>{{ item.title }}</b></h5>
                        <a class="btn btn-success rounded-pill"  href="{% url 'movieApplication:movieDetails' item.id %}"  style="font-family:fourier">View details</a>
                    </div>

                </div>
                <br>
            </div>


            {% elif request.user.is_superuser %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ item.title }}</td>
                <td>{{ item.description }}</td>
                <td>{{ item.release_date }}</td>
                <td>{{ item.duration }}</td>
                <td>{{ item.budget }}</td>
                <td>{{ item.rating }}</td>
                <td>
                    <img src="{{ item.poster.url }}">
                </td>
                <td>{{ item.category }}</td>
                <td>{{ item.language }}</td>
                <td>{{ item.status }}</td>
                <td><a class="btn btn-info rounded-pill" href="{{ item.trailer_url }}">Trailer</a></td>
                <td>
                    {% if item.active == 1 %}
                    <span>Active</span>
                    {% else %}
                    <span>Inactive</span>
                    {% endif %}
                </td>
                <td><a class="btn btn-success rounded-pill" href="{% url 'movieApplication:updateMovie' item.id %}" style="font-family:fourier">Update movie</a>
                    {% if item.active == 1 %}
                    <br>
                    <br>
                    <a class="btn btn-danger rounded-pill" href="{% url 'movieApplication:deleteMovie' item.id %}" style="font-family:fourier">Delete movie</a>
                    {% else %}
                    <a class="btn btn-info rounded-pill" href="{% url 'movieApplication:activateMovie' item.id %}" style="font-family:fourier">Activate movie</a>
                    {% endif %}
                </td>
            </tr>
            {% endif %}
            {% endfor %}
        </div>
    </div>
    </tbody>
</table>

{% endblock %}

proiectFinal/templates/aplicatie1/search_movies.html
{% extends 'base.html' %}
{% block content %}
    <center>
        {% if searched %}
          <h3>You searched for "{{ searched }}"</h3>
          <h4>We found this: </h4>
            <br/>
            {% for movie in movies %}
               <a href="{% url 'movieApplication:movieDetails' movie.id %}" style="font-size: 22px;">{{ movie.title }}</a> <br/>
            {% endfor %}
        {% endif %}
    </center>
{% endblock %}