proiect/aplicatie1/urls.py
from django.urls import path

from aplicatie1 import views

app_name = 'locations'

urlpatterns = [
    path('', views.LocationView.as_view(), name='lista_locatii'),
    path('add/', views.CreateLocationView.as_view(), name='add'),
    path('<int:pk>/update/', views.UpdateLocationView.as_view(), name='modifica'),
    path('<int:pk>/delete/', views.delete_location, name='sterge'),
    path('<int:pk>/activeaza/', views.activate_location, name='activeaza'),
    path('locatii_inactive', views.LocationInactiveView.as_view(), name='locatii_inactive')
]

proiect/aplicatie2/urls.py
from django.urls import path

from aplicatie2 import views

app_name = 'companies'

urlpatterns = [
    path('', views.CompanyView.as_view(), name='listare'),
    path('adaugare/', views.CreateCompanyView.as_view(), name='add'),
    path('<int:pk>/update/', views.UpdateCompanyView.as_view(), name='modify'),
    path('<int:pk>/delete/', views.delete_company, name='delete'),
    path('<int:pk>/activate/', views.activate_company, name='activate'),
    path('companies_inactive', views.CompanyInactiveView.as_view(), name='companies_inactive'),

]

proiect/myapi/urls.py
from django.urls import path, include
from rest_framework import routers

from myapi import views

router = routers.DefaultRouter()
router.register('location', views.LocationViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

proiect/proiect/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('locations/', include('aplicatie1.urls')),
    path('companies/', include('aplicatie2.urls')),
    path('profile/', include('userprofile.urls')),
    path('api/', include('myapi.urls')),

]

proiect/userprofile/urls.py
from django.urls import path

from userprofile import views

app_name = 'userprofile'

urlpatterns = [
    path('new_account/', views.CreateNewAccount.as_view(), name = 'utilizator_nou'),
    path('start_timesheet/', views.new_timesheet, name = 'start_pontaj'),
    path('stop_timesheet/', views.stop_timesheet, name = 'stop_pontaj'),

]

proiect/templates/base.html
<html>
<head >
    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css
">
</head>
<body>
<div class="container">
    <div class="row">
        <nav class="nav nav-pills nav-justified">
            <span> Hi, {{ request.user.username|upper }}!</span>
            <a class="btn btn-primary" href="/admin"> Admin</a>
            {% if request.user.is_authenticated %}
            <a class="btn btn-warning" href="{% url 'locations:lista_locatii'%}">Locatii active</a>
            <a class="btn btn-warning" href="{% url 'locations:locatii_inactive'%}">Locatii inactive</a>
            <a class="btn btn-info" href="{% url 'companies:listare'%}">Active companies</a>
            <a class="btn btn-info" href="{% url 'companies:companies_inactive'%}">Inactive companies</a>
            <a class="btn btn-dark" href="{% url 'userprofile:utilizator_nou'%}">Adaugare utilizator</a>
            <a class="btn btn-primary" href="{% url 'logout'%}">Logout</a>

          {% if ready_to_work is False %}
                        <a href="{% url 'userprofile:stop_pontaj' %}" class="btn btn-danger">Oprire pontaj</a>
                    {% else %}
                        <a href="{% url 'userprofile:start_pontaj' %}" class="btn btn-success">Pornire pontaj</a>
                    {% endif %}


            {% endif %}
        </nav>
    </div>

</div>
<br/>
{% block content %}
{% endblock %}
</body>
</html>