proiect/aplicatie2/urls.py
from django.urls import path

from aplicatie2 import views

app_name = 'companies'

urlpatterns = [
    path('', views.CompanyView.as_view(), name='listare'),
    path('adaugare/', views.CreateCompanyView.as_view(), name='add'),
    path('<int:pk>/update/', views.UpdateCompanyView.as_view(), name='modify'),
    path('<int:pk>/delete/', views.delete_company, name='delete'),
    path('<int:pk>/activate/', views.activate_company, name='activate'),
    path('companies_inactive', views.CompanyInactiveView.as_view(), name='companies_inactive'),

]

proiect/myapi/urls.py
from django.urls import path, include
from rest_framework import routers

from myapi import views

router = routers.DefaultRouter()
router.register('location', views.LocationViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

proiect/proiect/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('locations/', include('aplicatie1.urls')),
    path('companies/', include('aplicatie2.urls')),
    path('profile/', include('userprofile.urls')),
    path('api/', include('myapi.urls')),

]

proiect/aplicatie2/models.py
from django.db import models

# Create your models here.
from aplicatie1.models import Location

company_choices = (("SRL", "S.R.L."), ("SA", "S.A."))


class Companies(models.Model):
    name = models.CharField(max_length=100)
    website = models.CharField(max_length=100)
    company_type = models.CharField(max_length=10, choices=company_choices)
    active = models.BooleanField(default=1)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.company_type}"

proiect/aplicatie2/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView

from aplicatie2.models import Companies


class CompanyView(LoginRequiredMixin, ListView):
    model = Companies
    template_name = 'aplicatie2/companies_index.html'


class CreateCompanyView(LoginRequiredMixin, CreateView):
    model = Companies
    fields = ["name", "company_type", "website", "active", "location"]
    template_name = 'aplicatie2/companies_form.html'


    def get_success_url(self):
        return reverse('companies:listare')


class UpdateCompanyView(LoginRequiredMixin, UpdateView):
    model = Companies
    fields = ["name", "company_type", "website", "active"]
    template_name = 'aplicatie2/companies_form.html'

    def get_success_url(self):
        return reverse('companies:listare')

@login_required
def delete_company(request, pk):
    Companies.objects.filter(id=pk).update(active=0)
    return redirect('companies:listare')

@login_required
def activate_company(request, pk):
    Companies.objects.filter(id=pk).update(active=1)
    return redirect('companies:listare')

class CompanyInactiveView(LoginRequiredMixin, ListView):
    model = Companies
    template_name = 'aplicatie2/companies_index.html'

    def get_context_data(self, *args, **kargs):
        data = super(CompanyInactiveView, self).get_context_data( *args, **kargs)
        data['companies_list'] = self.model.objects.filter(active=0)
        return data

proiect/templates/aplicatie2/companies_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label }} {{ field }}
        {% endfor %}
        <button type="submit">Submit</button>
    </form>
{% endblock %}

proiect/templates/aplicatie2/companies_index.html
{% extends 'base.html' %}
{% block content %}
    <a class="btn btn-success" href="{% url 'companies:add' %}">Add company</a>
    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th>Index</th>
                <th>Company name</th>
                <th>Website</th>
                <th>Company type</th>
                <th>State</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for item in companies_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ item.name }}</td>
                    <td>{{ item.website }}</td>
                    <td>{{ item.company_type }}</td>
                    <td>{% if item.active == 1 %}
                            <span>Active</span>
                        {% else %}
                        <span>Inactive</span>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{% url 'companies:modify' item.id%}" class="btn btn-success">Modify</a>
                        {% if item.active == 1%}
                        <a href="{% url 'companies:delete' item.id%}" class="btn btn-danger">Delete</a>
                        {% else %}
                        <a href="{% url 'companies:activate' item.id%}" class="btn btn-info">Activate</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}