proiectFinal/aplicatie1/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

from aplicatie1 import views
from aplicatie1.views import MovieDetail

app_name = 'movieApplication'

urlpatterns = [
    path('', views.MoviesView.as_view(), name='lista_filme'),
    path('addMovie/', views.CreateMoviesView.as_view(), name='addMovie'),
    path('topRatedMovie/', views.MoviesTopRated.as_view(), name='topRatedMovie'),
    path('mostWatchedMovie/', views.MoviesMostWatched.as_view(), name='mostWatchedMovie'),
    path('recentlyAddedMovie/', views.MoviesRecentlyAdded.as_view(), name='recentlyAddedMovie'),
    path('<int:pk>/updateMovie/', views.UpdateMoviesView.as_view(), name='updateMovie'),
    path('<int:pk>/deleteMovie/', views.delete_movies, name='deleteMovie'),
    path('<int:pk>/activateMovie/', views.activate_movies, name='activateMovie'),
    path('inactiveMovies', views.MoviesInactiveView.as_view(), name='inactiveMovies'),
    path('searchMovies/', views.search_movies, name='searchMovies'),
    path('<int:pk>/movieDetails/', views.MovieDetail.as_view(), name='movieDetails'),
    path('register/', views.registerPage, name='register'),

    path('action/', views.MoviesAction.as_view(), name='action'),
    path('drama/', views.MoviesDrama.as_view(), name='drama'),
    path('comedy/', views.MoviesComedy.as_view(), name='comedy'),
    path('romance/', views.MoviesRomance.as_view(), name='romance'),
    path('adventure/', views.MoviesAdventure.as_view(), name='adventure'),
    path('love/', views.MoviesLove.as_view(), name='love'),
    path('cartoons/', views.MoviesCartoons.as_view(), name='cartoons'),


    # path('topRatedMovies', views.MoviesTopRated.as_view(), name='topRatedMovies'),
    # path('mostWatchedMovies', views.MoviesMostWatched.as_view(), name='mostWatchedMovies'),
    # path('recentlyAddedMovies', views.MoviesRecentlyAdded.as_view(), name='recentlyAddedMovies'),


]

proiectFinal/proiectFinal/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include


from proiectFinal import settings
from userprofile import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('movies/', include('aplicatie1.urls')),
    path('userprofile/', include('userprofile.urls')),


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proiectFinal/templates/base.html
<html>
<head>

    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">
</head>
<body style="background-color:">
<div class="container-fluid">
    <div class="row">
        <div class="col col-lg-13">
            <header class="header">
                <nav class="navbar navbar-dark bg-dark">
                    <span></span>
                    <a class="navbar-brand" style="font-size:36px; color:white; font-family:fourier;"><b>MovieMania</b></a>
                    {% if request.user.is_superuser %}
                    <a class="btn  btn-outline-warning rounded-pill" href="{% url 'movieApplication:lista_filme' %}"
                       style="font-family:fourier">ACTIVE MOVIES</a>
                    <br>
                    <br>
                    <br>
                    <a class="btn  btn-outline-warning rounded-pill" href="{% url 'movieApplication:inactiveMovies' %}"
                       style="font-family:fourier">INACTIVE MOVIES</a>
                    <br>
                    <br>
                    <br>
                    {% if request.user.is_superuser %}
                    <a class="btn btn-outline-warning rounded-pill" href="{% url 'movieApplication:addMovie' %}"
                       style="font-family:fourier">ADD MOVIE</a>
                    {% endif %}
                    <br>
                    <br>
                    <br>
                    <a class="btn  btn-outline-warning rounded-pill" href="/admin" style="font-family:fourier">ADMIN</a>
                    <br>
                    <br>
                    <br>
                    {% endif %}
                    {% if request.user.is_authenticated is False %}
                    <a class="btn btn-outline-warning rounded-pill" href="{% url 'login' %}">LOGIN</a>
                    <a class="btn btn-outline-warning rounded-pill" href="{% url 'movieApplication:register' %}">REGISTER</a>
                    {% elif request.user.is_authenticated %}
                    <form class="form-inline my-2 my-lg-0" method="POST"
                          action="{% url 'movieApplication:searchMovies' %}">
                        {% csrf_token %}
                        <input type="search" class="form-control mr-sm-3" placeholder="Search for a movie"
                               aria-label="Search" name="searched" aria-describedby="search-addon"
                               style="font-family:fourier"/>
                        <button class="btn btn-outline-warning my-2 my-sm-0 rounded-pill" type="submit"
                                style="font-family:fourier"> Search
                        </button>
                    </form>

                    <a class="btn btn-outline-warning rounded-pill" href="{% url 'logout' %}"
                       style="font-family:fourier">LOGOUT</a>
                    {% endif %}
                    <br>
                    <br>
                    <br>


                </nav>
            </header>
        </div>
    </div>
</div>
{% block content %}
{% endblock %}

</body>
</html>